<?php
$title = 'Log In';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('index', array('action' => 'login')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('login'));
echo $this->formRow($form->get('password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
        echo '<li>'.$message.'</li>';
    }
    echo '</ul>';
}